### ISSUE TITLE
clearRole

### ISSUE THREAD

**Issue by IdrisTheDragon** [AberDiscordBotsTeam/demoHelperBot#38]
https://github.com/AberDiscordBotsTeam/demoHelperBot/blob/6e3ff170f094260f0971e5c3366df142d62a3dae/cogs/demoHelper.py#L269

should use user.mention not the message author.mention

**Comment by JoelLucaAdams** [comment]
Thanks, the issue has now been resolved. Please see the commit fe8b8ecc392b4219de6183c2b2afb4a67285a517 for the patch
